### PR TITLE
Fixing import reshaper error and updating readme

### PR DESCRIPTION
**Pull request by b00f**
- Fixing reshaping error
- Suporting import library: https://manual.calibre-ebook.com/creating_plugins.html#a-user-interface-plugin
- Updating readme

### CODE REVIEW

**Comment by AndyKLB** [comment]
HI
I'm currently on 5.2.8 version and still the same problem of module named reshaper here is my log after trying to install if you have any solution it would be nice :)

"calibre, version 5.28.0
ERREUR : Exception non gérée: ModuleNotFoundError:No module named 'reshaper'

calibre 5.28 [64bit] embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Traceback (most recent call last):
File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
File "calibre\customize\ui.py", line 477, in add_plugin
File "calibre\customize\ui.py", line 65, in load_plugin
File "calibre\customize\zipplugin.py", line 293, in load
File "importlib_init_.py", line 127, in import_module
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "calibre\customize\zipplugin.py", line 192, in exec_module
File "calibre_plugins.dummy1.init", line 5, in
ModuleNotFoundError: No module named 'reshaper'
"

**Comment by b00f** [comment]
@And1k93 I have fixed this issue. I tried to find @0x414c49 at LinkedIn to approve this PR, but he didn't respond me. I don't want to maintain this project since I don't have time. You can use my fork and maintain the project. 

https://github.com/b00f/Calibre-KiPEO

**Comment by 0x414c49** [comment]
@b00f I don't have Calibre or Kindle to check how it works, does your PR fix the issue?

**Comment by b00f** [comment]
I have tested in mine. Probably should works because I have the updated device.

**Comment by 0x414c49** [comment]
@b00f I'll review the code and merge it soon. Thanks.

**Comment by AndyKLB** [comment]
> @b00f I'll review the code and merge it soon. Thanks.

Thank you for your work i'll wait for it 😊

**Comment by AndyKLB** [comment]
> @And1k93 I have fixed this issue. I tried to find @0x414c49 at LinkedIn to approve this PR, but he didn't respond me. I don't want to maintain this project since I don't have time. You can use my fork and maintain the project. 
> 
> 
> 
> https://github.com/b00f/Calibre-KiPEO

Sorry but i'm beginner and i don't know how ? I used your version but I think i must modify the code myself ? I didn't understand. 
Thank you for your time and your answer.

**Comment by b00f** [comment]
@And1k93 No need. It's already merged. Just use this library. Thanks

**Review by 0x414c49 — APPROVED** [review]

**Pull request merged**
